on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: charitybell/set-git-url-action@main
      - run: |
          UUID=$(cat /proc/sys/kernel/random/uuid)
          git checkout -b $UUID
          touch $UUID
          git add $UUID
          git commit -m $UUID
          git -c push.default=current push origin $UUID
          git ls-remote origin refs/heads/$UUID
          git push origin :$UUID
